Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission_7_Assignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission_7_Assignment.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket Basket { get; set; }

        public PurchaseController (IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            Basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (Basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = Basket.Items.ToArray();
                repo.SavePurchase(purchase);
                Basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission_7_Assignment.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission_7_Assignment.Infrastructure;
using Mission_7_Assignment.Models;

namespace Mission_7_Assignment.Pages
{
    public class ShoppingCartModel : PageModel
    {
        //private double price;

        private IBookstoreRepository repo { get; set; }
        public Basket Basket { get; set; }
        public string ReturnUrl { get; set; }

        public ShoppingCartModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            Basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);
            double p = repo.Books.FirstOrDefault(x => x.BookId == bookId).Price;

            Basket.AddItem(b, 1, p);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            Basket.RemoveItem(Basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new {ReturnUrl = returnUrl});
        }
    }
}

Pages/PurchaseCompleted.cshtml
@page
@model Mission_7_Assignment.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Your items have been purchased!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Pages/ShoppingCart.cshtml
@page
@model Mission_7_Assignment.Pages.ShoppingCartModel
@{
}

<h2>Your Shopping Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.Basket.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>@(i.Book.Price.ToString("c"))</td>
                    <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="bookId" value="@i.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.Basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Purchase" asp-action="Checkout" >Checkout</a>
</div>

Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">The Bookstore</span>
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>